### ISSUE TITLE
使用该脚本出现这个问题该如何解决?

### ISSUE THREAD

**Issue by 954455850** [wxlost/ServerStatus-HostLoc#2]
![image](https://user-images.githubusercontent.com/31529293/98439998-db173000-20ed-11eb-80f2-b40441acb303.png)

使用该脚本出现这个问题该如何解决?

**Comment by 954455850** [comment]
腾讯轻量云 centos 7.6

**Comment by 954455850** [comment]
![image](https://user-images.githubusercontent.com/31529293/98439994-d05c9b00-20ed-11eb-98e8-82defd8b5e9d.png)

**Comment by wxlost** [comment]
你好.这款探针由于机器太多在访问的时间比较吃资源.我已经弃用了.脚本都是开源的可以自己修一下吗.看报错是下载caddy的地址错了.

**Comment by 954455850** [comment]
emmm,我只是一个只会用一键脚本的小白,如果不能修的话,打扰您了,不好意思....

**Comment by wxlost** [comment]
> emmm,我只是一个只会用一键脚本的小白,如果不能修的话,打扰您了,不好意思....

目前用的这款
```
https://github.com/p14yground/nezha
```

**Comment by 954455850** [comment]
> > emmm,我只是一个只会用一键脚本的小白,如果不能修的话,打扰您了,不好意思....
> 
> 目前用的这款
> 
> ```
> https://github.com/p14yground/nezha
> ```

**Comment by 954455850** [comment]
谢谢哈,我试试
